### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by YuanXinCherry** [RQuispeC/saliency-semantic-parsing-reid#4]
Traceback (most recent call last):
  File "test_two_nets_img.py", line 266, in <module>
    main()
  File "test_two_nets_img.py", line 149, in main
    checkpoint = torch.load(args.resume2)
  File "/home/jy/.conda/envs/reid/lib/python3.6/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/jy/.conda/envs/reid/lib/python3.6/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 1: ordinal not in range(128)

**Comment by RQuispeC** [comment]
It seems like a problem loading the models, specifically the second model. Have check trying to load the first model twice? Or download the second model again to double check  that the file is not corrupted?

**Comment by YuanXinCherry** [comment]
Yes, there is no problem with the first model loading, but the second model loading has the same problem. I also tried to download the second model again, but it was the same error

**Comment by RQuispeC** [comment]
does this happen with the models for all datasets?
did you make sure that -a1, --resume1 are used for the saliency network and -a2, --resume2 for the parsing network?

**Comment by YuanXinCherry** [comment]
So far,I have only tested it on Market1501， and I make sure that -a1, --resume1 are used for the saliency network and -a2, --resume2 for the parsing network.

**Comment by RQuispeC** [comment]
It's weird that it can load model 1 successfully (--resume1) but not model 2, my only guess here is that there is a problem with the file or/and pytorch function [load](https://pytorch.org/docs/stable/torch.html?highlight=torch%20load#torch.load), I used an old version of pytorch for this repo (V0.4.0) maybe that's the reason. I would suggest to try the models for other datasets and also check pytorch's documentation to see if the version is related.

I will leave this issue open, please keep us posted if you find a solution. Sorry I can't help you more at this time

**Comment by haveadrame** [comment]
![Snipaste_2023-03-07_19-59-37](https://user-images.githubusercontent.com/122344708/223416097-4647903f-45c5-4920-a0f2-1cc0d8de180d.png)
Excuse me, what is this about?
Can you help me?

**Comment by YuanXinCherry** [comment]
Training process？

**Comment by haveadrame** [comment]
Have you found this file python train_blah_blah.py -h, or do you have their parameters? Can you share them with me?
